#!/bin/bash
# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2 License
# The full license information can be found in LICENSE.txt
# in the root directory of this project.

set -x
echo "Pre-Install Steps"
echo "Stopping the Axon"
sudo systemctl stop axon
echo "Removing axon directory"
sudo rm -fr /opt/axon/*
